version: '3.0'
services: 
    redis-server: 
        image: 'redis'
        command: redis-server --requirepass ayushwalia
    node-app:
        build: .
        # port mapping similar to 'docker run' command
        ports:
            - "8000:8000"
            # defines the restart condition - default is never
        restart: "on-failure"
