version: '3.7'

services:

    client-build:
        build:
            context: ./fibonacci
        volumes:
            - cra-volume:${TMP_PATH}/build
        environment:
            - NODE_ENV
            - TMP_PATH

    redis-server: 
        image: 'redis:latest'
        # Specifying the environment file here
        command: sh -c "redis-server --requirepass \"${REDIS_PASSWORD}\" --appendonly yes"
        volumes:
            - /tmp/data:/data
        environment: 
            - REDIS_PASSWORD
            
    node-app:
        build: 
            dockerfile: Dockerfile.Dev
            context: ./server
        # port mapping similar to 'docker run' command
        ports:
            - "8000:8000"
            # defines the restart condition - default is never
        restart: "on-failure"
        # Specifying the environment file here
        volumes: 
            - cra-volume:${TMP_PATH}/public
        environment: 
            - TMP_PATH
            - REDIS_PASSWORD
            - REDIS_PORT
            - REDIS_HOST

volumes:
    cra-volume:
        external: false